windowrule=match:class ^(org.telegram.desktop)$, no_screen_share on
windowrule=match:class ^(org.keepassxc.KeePassXC)$, no_screen_share on
windowrule=match:class ^(Mattermost)$, no_screen_share on
windowrule=match:class ^(KeepChat)$, no_screen_share on
windowrule=match:class ^(org.mozilla.Thunderbird)$, no_screen_share on
