font_family      family="Iosevka Nerd Font Mono"
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

scrollback_lines -1

cursor_shape beam
cursor_trail 1

window_margin_width 10
confirm_os_window_close 0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map shift+page_up    scroll_page_up
map shift+page_down    scroll_page_down

map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+0 change_font_size all 0


# BEGIN_KITTY_THEME
# Dracula
# include current-theme.conf
# END_KITTY_THEME
