exec-once = kanshi
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = hyprsunset
exec-once = uv --directory ~/.config/hypr/scripts run events-handler.py
exec-once = gnome-keyring-daemon --start --components=secrets
exec = snappy-switcher --daemon
