bind = Super, Q, killactive,
bind = Super+Shift+Alt, Q, exec, hyprctl kill

bind = Super, F1, workspace, 1
bind = Super, F2, workspace, 2
bind = Super, F3, workspace, 3
bind = Super, F4, workspace, 4
bind = Super, F5, workspace, 5
bind = Super, F6, workspace, 6
bind = Super, F7, workspace, 7
bind = Super, F8, workspace, 8
bind = Super, F9, workspace, 9
bind = Super, F10, workspace, 10
bind = Super, F11, workspace, 11
bind = Super, F12, workspace, 12

bind = Super+Shift, F1, movetoworkspace, 1
bind = Super+Shift, F2, movetoworkspace, 2
bind = Super+Shift, F3, movetoworkspace, 3
bind = Super+Shift, F4, movetoworkspace, 4
bind = Super+Shift, F5, movetoworkspace, 5
bind = Super+Shift, F6, movetoworkspace, 6
bind = Super+Shift, F7, movetoworkspace, 7
bind = Super+Shift, F8, movetoworkspace, 8
bind = Super+Shift, F9, movetoworkspace, 9
bind = Super+Shift, F10, movetoworkspace, 10
bind = Super+Shift, F11, movetoworkspace, 11
bind = Super+Shift, F12, movetoworkspace, 12

bind = Super+Shift, R, exec, ~/.config/hypr/scripts/rename_workspace.sh

bind = Super,TAB,workspace,previous
bind = Super, Escape, exec, rofi -show workspace -modi "workspace:~/.config/hypr/scripts/rofi_workspace_switcher.sh"
bind = ALT, Tab, exec, snappy-switcher next
bind = ALT SHIFT, Tab, exec, snappy-switcher prev

bind = Super, Z, exec, bash ~/.config/hypr/scripts/toggle_overlay_workspace.sh
bind = Super, grave, togglespecialworkspace, term

bind = Super, Return, exec, kitty -1
bind = Super, W, exec, firefox
bind = Super, E, exec, nautilus

bindr = Super, Super_L, exec, rofi -show drun

bindm=Super,mouse:272,movewindow
bindm=Super,mouse:273,resizewindow

bind = Super, Left, movefocus, l
bind = Super, Right, movefocus, r
bind = Super, Up, movefocus, u
bind = Super, Down, movefocus, d

bind = Ctrl+Alt, Left, layoutmsg, focus left
bind = Ctrl+Alt, Right, layoutmsg, focus right

bindle=, XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindle=, XF86MonBrightnessDown, exec, brightnessctl s 5%-

bindle=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+
bindle=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindl = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle

bindl= ,XF86AudioNext, exec, playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"`
bindl= ,XF86AudioPrev, exec, playerctl previous
bindl= ,XF86AudioPlay, exec, playerctl play-pause
bindl= ,XF86AudioPause, exec, playerctl play-pause

binde = Super, minus, splitratio, -0.1
binde = Super, equal, splitratio, +0.1
bind = Super, Space, togglefloating,
bind = Super, D, fullscreen, 1
bind = Super, F, fullscreen, 0
bind = Super, slash, layoutmsg, colresize 0.5
bind = Super+Shift, slash, layoutmsg, colresize all 0.5
bind = Super, backslash, layoutmsg, colresize 1
bind = Super+Shift, backslash, layoutmsg, colresize all 1
bind = Super+Shift, period, layoutmsg, colresize +0.1
bind = Super+Shift, comma, layoutmsg, colresize -0.1

bind = Super, L, exec, hyprlock
bind = Ctrl+Alt, Delete, exec, rofi -show power-menu -modi power-menu:rofi-power-menu 

bind = , Print, exec , grimblast copy area
