set -g mouse on
set -sg terminal-overrides ",*:RGB"

set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cpu-usage ram-usage network-bandwidth uptime"
set -g @dracula-show-left-icon "#h | #S"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
